export const SPECIALIZATIONS = [
  "Applied Behavior Analysis (ABA)",
  "Behavioral Therapy",
  "Occupational Therapy",
  "Physical Therapy",
  "Speech-Language Pathology",
  "Developmental Pediatrics",
  "Developmental Dentistry",
  "Pediatric Dentistry",
  "Pediatric Neurology",
  "Child & Adolescent Psychiatry",
  "Psychiatry",
  "Psychology",
  "Genetics & Metabolic Disorders",
  "Community Medicine",
  "Special Education",
  "Social Work",
  "Rehabilitation Medicine",
  "Nutrition & Dietetics",
  "Nursing (IDD Care)",
]
